/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.Bilet;
import DAO.Musteri;
import Services.BonusPuanService;
import Services.MusteriService;
import javax.swing.JOptionPane;

/**
 *
 * @author sefercanaydas
 */
public class BiletOdeme extends javax.swing.JFrame {
    BonusPuanService bonusPuanServis;
    MusteriService musteriServis;
    Bilet alinacakBilet;
    Musteri alicakMusteri;
     /**
     * Creates new form BiletOdeme
     * @param alinacakBilet
     * @param alicakMusteri
     */
    public BiletOdeme(Bilet alinacakBilet,Musteri alicakMusteri) {
        initComponents();
        bonusPuanServis = new BonusPuanService();
        musteriServis = new MusteriService();
        this.alinacakBilet = alinacakBilet;
        this.alicakMusteri = alicakMusteri;
        txtFirma.setText(alinacakBilet.getFirma().toString());
        txtTarih.setText(alinacakBilet.getTarih().toString());
        txtCikis.setText(alinacakBilet.getCikisIl().toString());
        txtVaris.setText(alinacakBilet.getVarisIl().toString());
        txtFiyat.setText(alinacakBilet.getFiyat().toString());
        txtBonusPuan.setText("%"+bonusPuanServis.getBonusPuan(alinacakBilet.getFirma().getId()));
        txtMusteriBonusPuan.setText(alicakMusteri.getHediyePuan()+"");
        txtOdenecekTutar.setText(alinacakBilet.getFiyat()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirma = new javax.swing.JTextField();
        txtTarih = new javax.swing.JTextField();
        txtCikis = new javax.swing.JTextField();
        txtVaris = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFiyat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBonusPuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMusteriBonusPuan = new javax.swing.JTextField();
        checkBonusPuan = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtOdenecekTutar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Firma:");

        jLabel2.setText("Tarih:");

        jLabel3.setText("Çıkış Noktası:");

        jLabel4.setText("Varış Noktası:");

        txtFirma.setEditable(false);

        txtTarih.setEditable(false);

        txtCikis.setEditable(false);

        txtVaris.setEditable(false);

        jLabel5.setText("Fiyat:");

        txtFiyat.setEditable(false);

        jLabel6.setText("Firma Bonus:");

        txtBonusPuan.setEditable(false);

        jLabel7.setText("Müşteri Bonus Puan:");

        txtMusteriBonusPuan.setEditable(false);

        checkBonusPuan.setText("Bonus Puan Kullanmak İstiyorum");
        checkBonusPuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBonusPuanActionPerformed(evt);
            }
        });

        jLabel8.setText("Ödenecek Tutar :");

        txtOdenecekTutar.setEditable(false);

        jButton1.setText("Öde");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Nakit Öde");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Kredi Kartı ");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Çek ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirma)
                    .addComponent(txtTarih)
                    .addComponent(txtCikis)
                    .addComponent(txtVaris)
                    .addComponent(txtFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtBonusPuan))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMusteriBonusPuan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(checkBonusPuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(28, 28, 28)
                            .addComponent(txtOdenecekTutar))
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtMusteriBonusPuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBonusPuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCikis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtOdenecekTutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBonusPuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBonusPuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBonusPuanActionPerformed
        // TODO add your handling code here:
        if (checkBonusPuan.isSelected()) {
            txtOdenecekTutar.setText((alinacakBilet.getFiyat() - alicakMusteri.getHediyePuan())+"");
        }else{
            txtOdenecekTutar.setText(alinacakBilet.getFiyat()+"");
        }
    }//GEN-LAST:event_checkBonusPuanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        musteriServis.satisYap(alicakMusteri, alinacakBilet.getFiyat(), bonusPuanServis.getBonusPuan(alinacakBilet.getFirma().getId()), checkBonusPuan.isSelected());
        JOptionPane.showConfirmDialog(this, "Ödeme Başarıyla Tamamlandı", "Ödeme", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiletOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiletOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiletOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiletOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiletOdeme(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBonusPuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField txtBonusPuan;
    private javax.swing.JTextField txtCikis;
    private javax.swing.JTextField txtFirma;
    private javax.swing.JTextField txtFiyat;
    private javax.swing.JTextField txtMusteriBonusPuan;
    private javax.swing.JTextField txtOdenecekTutar;
    private javax.swing.JTextField txtTarih;
    private javax.swing.JTextField txtVaris;
    // End of variables declaration//GEN-END:variables
}
